=== jlokiec/PKCK-1/zadanie1.dtd
<!ELEMENT document (header, musicians, genres, languages, distributors, catalog)>
        <!ELEMENT header (authors, description, modificationDate)>
        <!ELEMENT authors (author)+>
        <!ELEMENT author (name, surname, studentId)>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT surname (#PCDATA)>
        <!ELEMENT studentId (#PCDATA)>
        <!ELEMENT description (#PCDATA)>
        <!ELEMENT modificationDate (#PCDATA)>

        <!ELEMENT musicians (musician)*>
        <!ELEMENT musician (name, surname?)>
        <!ATTLIST musician musicianId ID #REQUIRED>

        <!ELEMENT genres (genre)*>
        <!ELEMENT genre EMPTY>
        <!ATTLIST genre genreId ID #REQUIRED
                genreName CDATA #REQUIRED>

        <!ELEMENT languages (language)*>
        <!ELEMENT language (#PCDATA)>
        <!ATTLIST language languageId ID #REQUIRED>

        <!ELEMENT distributors (distributor)*>
        <!ELEMENT distributor (#PCDATA)>
        <!ATTLIST distributor distributorId ID #REQUIRED>

        <!ELEMENT catalog (cd)*>

        <!ELEMENT cd (title, coverImg, premiereDate, numberOfCds, price)>
        <!ATTLIST cd musicianId IDREF #REQUIRED
                genreId IDREF #REQUIRED
                languageId IDREF #REQUIRED
                distributorId IDREF #REQUIRED>
        <!ELEMENT title (#PCDATA)>
        <!ELEMENT coverImg EMPTY>
        <!ATTLIST coverImg src CDATA #REQUIRED>
        <!ELEMENT premiereDate (#PCDATA)>
        <!ELEMENT numberOfCds (#PCDATA)>

        <!ELEMENT price (#PCDATA)>
        <!ATTLIST price currency (PLN | USD) #REQUIRED>

=== jlokiec/PKCK-1/zadanie1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<?xml-stylesheet type="text/css" href="zadanie1.css"?>
<!--<!DOCTYPE bookStore SYSTEM "zadanie1.dtd">-->
<document>
    <header>
        <authors>
            <author>
                <name>Maciej</name>
                <surname>Cierpikowski</surname>
                <studentId>210153</studentId>
            </author>
            <author>
                <name>Jakub</name>
                <surname>Łokieć</surname>
                <studentId>210259</studentId>
            </author>
        </authors>
        <description>Katalog płyt CD z muzyką</description>
        <modificationDate>11.03.2019</modificationDate>
    </header>
    <catalog>
        <cd>
            <title>A Star is Born</title>
            <musician>Lady Gaga</musician>
            <musician>Bradley Cooper</musician>
            <genre>Muzyka filmowa</genre>
            <premiereDate>19.10.2018</premiereDate>
            <language>EN</language>
            <numberOfCds>1</numberOfCds>
            <distributor>Universal Music Polska</distributor>
            <price>39,99</price>
        </cd>
        <cd>
            <title>The Greatest Hits I, II & III</title>
            <musician>Queen</musician>
            <genre>Rock</genre>
            <premiereDate>24.06.2011</premiereDate>
            <language>EN</language>
            <numberOfCds>3</numberOfCds>
            <distributor>Universal Music Polska</distributor>
            <price>59,99</price>
        </cd>
    </catalog>
</document>
